FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrate

WORKDIR /app

COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet restore

CMD [ "/bin/sh", "./init-db.sh" ]

